import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import Provider from "@/context/provider";
export const metadata = {
    title: "Students Get Rentals",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    {children}
                    </Provider>
                    
            </body>
        </html>
    );
}
